### ISSUE TITLE
Bug: Hours is Not Ignored in Timeago

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/Glancer#10]
I coded to make 'time ago' readable and sensible for up to 5 years based on the existing comment date creation.

It works fine, EXCEPT:
- I've noticed any comments which have been created within 'hours' and not 'days' still go through my code and then show the default 'over 5 years ago`

I was expecting the Kanboard '5h' or '~5h' as it is in the core but it seems ignored. I'd like to change the 'h' to 'hrs' or 'hours' but the code in the function is complicated to strip. Days is more important in workload anyway so i got that working.

I need help with the code to ignore the minutes and hours

![image](https://user-images.githubusercontent.com/10233708/200114532-eed7441f-2551-4d69-b3cd-c940e3ea7fed.png)

The tooltip is the correct value in the picture

Commit: cfbf1fe

**Comment by aljawaid** [comment]
Still cant get it to work :(

**Comment by creecros** [comment]
now it does, ill leave the rest to you

**Comment by aljawaid** [comment]
Fixed by 77c76fe
