### ISSUE TITLE
Bug: Normal Users Login Issue

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/Glancer#14]
When normal (non-admin) users login with Glancer installed, after logging in, the user is directed to a page not found message.  Clicking on the dashboard icon takes them to the dashboard. But straight after login, the first page, which should be the dashboard, is the not found page (which is blank, just the header and glancer bar).

**Comment by creecros** [comment]
does it for any user for me.

I understand what's going on, it is in the route. `:link:` which is undefined on plugin initialization, so it overrides the main route to the dashboard, by going through our controller.

I didn't think of that...will have to think about it.

**Comment by aljawaid** [comment]
great, thanks

**Comment by creecros** [comment]
Test that
Seems to work, but maybe i missed something.

**Comment by aljawaid** [comment]
> Test that Seems to work, but maybe i missed something.

ok I will test but you removed the whole url and the function and the test for the project_id url change.... wait let me test before i confuse things more

**Comment by creecros** [comment]
I did, completely removed the route all together, and tried to find a way to run through the existing routes of kanboard. I think this succeeded.

**Comment by aljawaid** [comment]
> Test that Seems to work, but maybe i missed something.

tested, seems to be fixed... highly appreciated
