### ISSUE TITLE
Project Overview Link Button in Comment

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/Glancer#15]
I Cant seem to get this to work:

I replaced the activity template to add a css ID which will target from the comments through an icon.

`<?= $this->url->icon('eye', t('Overview'), 'ProjectOverviewController', 'show', array('project_id' => $task['project_id']), false, 'comment-board', 'View recent activity in this project', false, 'ActivityOverview') ?>`

in the addressbar, it works:
`domain.com/project/37/overview#ActivityOverview`

**Comment by aljawaid** [comment]
@creecros do you think it's the routing?

**Comment by creecros** [comment]
I fix one thing and you give me another! 😀

**Comment by creecros** [comment]
push the code please so I can see everything

**Comment by aljawaid** [comment]
> I fix one thing and you give me another! 😀

haha so sorry about that

**Comment by creecros** [comment]
`<?= $this->url->icon('eye', t('Overview'), 'ProjectOverviewController', 'show', array('project_id' => $task['project_id']), false, 'comment-board', 'View recent activity in this project', false, '') ?>`


What is the point of `#ActivityOverview`? I don't see a reference for that to find.

**Comment by creecros** [comment]
I lied, i see it now.

**Comment by creecros** [comment]
just don't use a controller, you have every variable you need in the template to build the link.

**Comment by creecros** [comment]
wow, even a hard link won't actually work...i'm not going to lie, i'm confused.

**Comment by creecros** [comment]
i figured it out. It's your JS. everything works if you turn it off.

**Comment by aljawaid** [comment]
great thanks for that I will look into it tonight
