### ISSUE TITLE
Feature request:  ability to add a href link and text or image in Glancer 

### ISSUE THREAD

**Issue by Jeager2** [aljawaid/Glancer#21]
I have an external wiki that I use for documentation and would very much like a link to the wiki board directly and always visible within the kanboard. What I am requesting is the ability to add a link and text in Glancer that is always visible. Glancer seems like an ideal candidate because of its visibility within the kanboard itself. Thanks for your consideration.

**Comment by aljawaid** [comment]
Hello, let me look into this... although I have not done user-saved fields before and the Kanboard docs are very poor generally.

If I ca do it, it would probably be on the right of the bar.... but... whats the name of your wiki? Or how many characters long is it so I can provision the space.... maybe even replace with a generic icon instead of a word to save space.

All open ideas for now.

**Comment by Jeager2** [comment]
It’s A&F wiki 
However a generic icon would be excellent instead. I’d be happy with either possibility.

**Comment by aljawaid** [comment]
@Jeager2 choose two....  1st choice and 2nd

![image](https://user-images.githubusercontent.com/10233708/204384318-185684e5-55df-4cf5-93a2-3e31efdc8dbc.png)

![image](https://user-images.githubusercontent.com/10233708/204384701-8140957f-a9e7-41cc-8b6e-4869e6a6f57d.png)

**Comment by Jeager2** [comment]
How about “bookmarks” and “journals”?

**Comment by Jeager2** [comment]
I do like the book icon too

**Comment by aljawaid** [comment]
I liked this book so I started on it whilst I was waiting for your reply... looks different, looks decent...?

The icon is yet to be made white... the whole bar is being re-aligned
![image](https://user-images.githubusercontent.com/10233708/204402570-50664348-89c3-48fb-a807-f0853901a5b2.png)

**Comment by aljawaid** [comment]
> How about “bookmarks” and “journals”?

boring... comeone spice it up.... `journal-bookmark-fill` is way better or `journal-bookmark` from that set

**Comment by aljawaid** [comment]
this is nice....
![image](https://user-images.githubusercontent.com/10233708/204404707-95fd2ef9-bc64-448a-a232-978a403bb4fa.png)

**Comment by Jeager2** [comment]
That looks great. How are you handling where someone would put the url in? 
settings > Glancer ?

**Comment by aljawaid** [comment]
- [ ] Make room for icon
- [ ] Create field to store label/link value

**Comment by creecros** [comment]
just use metadata to store the link.

**Comment by aljawaid** [comment]
> just use metadata to store the link.

how does that work? is it per user? I dont seem to understand whether I need to create a schema for it... I only know basic mysql

**Comment by creecros** [comment]
no schema.

https://docs.kanboard.org/v1/plugins/metadata/

you can look at customizer, metamagik, group assign, or just about any of my plugins for usage examples.

**Comment by Jeager2** [comment]
Just wanted to express my appreciation for working on this feature. Do you know (after you've finished) how long it will take to show up as an update in the plugin directory? Thanks again!

**Comment by aljawaid** [comment]
> Just wanted to express my appreciation for taking the time to working on this feature. Do you know (after you've finished) how long it will take to show up as an update in the plugin directory? Thanks again!

hey to be honest, without @creecros none of this is possible. As soon as Im happy it all works, a day after I have closed the issues, I will release a new version.  My last updates are still pending to be published in the directory since 6 days so I'm not sure whats going on.  Usually frederic would push updates to the directory daily.

**Comment by Jeager2** [comment]
That looks excellent! Can’t wait to try it!

**Comment by aljawaid** [comment]
Now released in https://github.com/aljawaid/Glancer/releases/tag/v2.0
