### ISSUE TITLE
Add Plugin Settings Page

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/Glancer#23]
Will need to save values for #21

**Comment by aljawaid** [comment]
@creecros 
```
<a
		href="#"
		class="glancer-extra"
		title="<?= $this->configModel->get('tooltip_title', '') ?>"
		target="_blank">test</a>
```
Please explain how I am meant to call the setting.  Im getting a white screen right now and Im really confused on how to call the setting... I already tried the `if (!empty)`

**Comment by aljawaid** [comment]
```
<a
href="#"                                 // text field in settings
class="glancer-extra"
rel="noreferrer noopener"      //checkbox in settings
title=""                                   //text field in settings
target="_blank">                   //check box in settings
```

**Comment by aljawaid** [comment]
@creecros 
`<?= $this->configModel->get('tooltip_title', '') ?>` doesnt work
`<?= $this->task->configModel->get('tooltip_title', '') ?>` this works on the text field (not even in the docs)
...but we working the config side, not in the task...

**Comment by aljawaid** [comment]
> @creecros `<?= $this->configModel->get('tooltip_title', '') ?>` doesnt work `<?= $this->task->configModel->get('tooltip_title', '') ?>` this works on the text field (not even in the docs) ...but we working the config side, not in the task...

@creecros please explain... is it okay to use `this task` for this plugin when it has nohing to do with tasks (for the config settings pages)

**Comment by creecros** [comment]
ues, in a template it is $this->task->configModel

**Comment by creecros** [comment]
> @creecros
> 
> ```
> <a
> 		href="#"
> 		class="glancer-extra"
> 		title="<?= $this->configModel->get('tooltip_title', '') ?>"
> 		target="_blank">test</a>
> ```
> 
> Please explain how I am meant to call the setting. Im getting a white screen right now and Im really confused on how to call the setting... I already tried the `if (!empty)`

`$this->task->configModel->get('tooltip_title', '')`  the last `''` in this is your default value, if it is empty. So you can actually put a default link in there, i.e. `$this->task->configModel->get('tooltip_title', 'http://mydefault.com')`

**Comment by aljawaid** [comment]
> yes, in a template it is `$this->task->configModel`, anywhere else, it would just be `$this->configModel`
> 
> and yes, the docs leave that out, but my examples i gave should help in the usage.

yeh your examples help alot but with a generic word like 'task' it confused the hell out of me as we have a 'tast' feature in kanboard.... the docs should be more detailed.  the new version is harder to read and feels like more information has removed.  been 7 days since my PR hasnt gone through either for the plugins.json.... not sure if i should still continue working on kanboard

**Comment by creecros** [comment]
ya, i dont know whats going on with either of those, im the same as you, just some guy who at one point in time enjoyed working on kanboard. i really only use it to keep my mind occupied and help increase my programming aptitude. i should probably devote time to docpht, since i at least have skin in that game.

**Comment by aljawaid** [comment]
@creecros I dont understand why this is not working in the template.... only if i complete the blank value will it show but the whole point is not to have a blank value
```
rel="<?php if ($this->task->configModel->get('not_allowed_tracking', '') == 'not_allowed_tracking'): ?> noreferrer noopener <?php endif ?>"
```

**Comment by aljawaid** [comment]
![image](https://user-images.githubusercontent.com/10233708/204949547-b1cd026d-e98e-42af-8225-9a86a96d2f60.png)
