### ISSUE TITLE
This is another feature request. (as a new plugin)

### ISSUE THREAD

**Issue by Jeager2** [aljawaid/Glancer#24]
I'm sorry, I did not see how to write you without making it an "issue"

Have you heard of mermaid? It allows simple text to become a diagram.

Where i came across the idea:
https://kanboard.discourse.group/t/new-plugin-addmermaid/2392

I do not see any plugins that allow it yet, however I was able to simply add it to my plugins directory and now I can draw diagrams easily!
So awesome, I wanted the community to have this ability and it should be a piece of cake for you to create as a plugin.

Mermaids main site:
https://mermaid-js.github.io/mermaid/#/

Code example in any task's description that will diagram once installed:
```
<div class="mermaid">
sequenceDiagram
    Alice->>John: Hello John, how are you?
    John-->>Alice: Great!
    Alice-)John: See you later!
</div>
```

A second example:
```
<div class="mermaid">
flowchart LR
    A-->B
    B-->C
    C-->D
    D-->E
    click A "https://www.github.com" _blank
    click B "https://www.github.com" "Open this in a new tab" _blank
    click C href "https://www.github.com" _blank
    click D href "https://www.github.com" "Open this in a new tab" _blank
</div>

```
My request: Please can you make a simple plugin so others may install this easily ?

Best wishes,
Faisal

**Comment by Jeager2** [comment]
To show how simple it is to get working...

What I did:

Downloaded this:
https://github.com/euneuber/AddMermaid/archive/refs/heads/main.zip

Copied the contents here:
Kanboard/www/app/plugins/AddMermaid

That's it... it works

**Comment by Jeager2** [comment]
The above code renders like this"
[][(url](https://imgur.com/a/nkRYZ1d))

**Comment by aljawaid** [comment]
Salaam Faisal, this is ALREADY a plugin and exists https://github.com/euneuber/AddMermaid/tags

**Comment by aljawaid** [comment]
> I wanted the community to have this ability and it should be a piece of cake for you to create as a plugin.

haha not really, anyway, you can easily create a basic plugin using the starter template I created [KanboardSkeletonPlugin](https://github.com/aljawaid/KanboardSkeletonPlugin)

**Comment by aljawaid** [comment]
> Salaam Faisal, this is ALREADY a plugin and exists https://github.com/euneuber/AddMermaid/tags

Always install plugins following the instructions that come with each plugin.  In all of my plugin readmes, inline with https://github.com/aljawaid/KanboardSkeletonPlugin the installation methods are the safest way.  Just copying the repository may not be wise as they are mostly a 'work in progress'.
