### ISSUE TITLE
Add Dashboard Default for Bad Comment ID Inputs by User

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/Glancer#3]
you can default to the dashboard in the controller if a bad id is input.

_Originally posted by @creecros in https://github.com/aljawaid/Glancer/issues/1#issuecomment-1296519433_

**Comment by aljawaid** [comment]
Fixed by #2 Add URL Route for Pretty URLS

**Comment by creecros** [comment]
I didn't fix this yet
