### ISSUE TITLE
PHP Deprecated:  str_replace()

### ISSUE THREAD

**Issue by creecros** [aljawaid/Glancer#5]
To fix:

`2022/10/31 17:49:37 [error] 15#15: *45 FastCGI sent in stderr: "PHP message: PHP Deprecated:  str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in /var/www/app/app/Core/Http/Route.php on line 155`

Just need to add a empty parameter, when I or you get a chance. Just a annoying deprecated message.

**Comment by aljawaid** [comment]
> To fix:
> 
> `2022/10/31 17:49:37 [error] 15#15: *45 FastCGI sent in stderr: "PHP message: PHP Deprecated: str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in /var/www/app/app/Core/Http/Route.php on line 155`
> 
> Just need to add a empty parameter, when I or you get a chance. Just a annoying deprecated message.

put it where though? in the core kanboard file? `str_replace()` isnt found in the plugin... or am I looking in the wrong place probably...

**Comment by creecros** [comment]
no no, its a deprecated warning. in php 7.4 you could have a null param, in php 8 and above you have to send all parameters if listed,  so just need to add all the parameters, its in our controller, I only sent the parameters I needed.

**Comment by creecros** [comment]
might be in the addroute, which I don't even need anymore, don't worry about it, I'll take care of it.
